name: presentation
description: Presentation layer
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  data:
    path: ../data
  domain:
    path: ../domain
  flutter_svg: ^0.22.0
  firebase_core: ^1.13.1
  firebase_analytics: ^9.1.3
  firebase_crashlytics: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mockito: ^5.1.0
  build_runner: ^2.1.8

flutter:
  generate: true

  assets:
    - ../../assets/svg/




