name: presentation
description: Presentation layer
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  
  data:
    path: ../data
  domain:
    path: ../domain

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - ../../assets/svg/